x-motemen/gore

liner.go
main.go
terminal_unix.go
terminal_windows.go

I implemented a feature to indent continuing code using text/scanner.
It increases the indent depth by '{' token, and decreases it by '}' token.

Indent code in continue mode

---

README.adoc
main.go
session_test.go

This PR provides `auto-importing` to gore by using [golang.org/x/tools/imports](https://godoc.org/golang.org/x/tools/imports) package.
The package adds or removes import statements as necessary.
It works like the following:
```
gore version 0.0.0  :help for help
gore> filepath.Join("a", "b")
"a/b"
gore> strings.TrimPrefix("ab", "a")
"b"
gore> :print
package main
import (
"fmt"
"path/filepath"
"strings"
)
func __gore_p(xx ...interface{}) {
for _, x := range xx {
fmt.Printf("%#v\n", x)
}
}
func main() {
filepath.Join("a", "b")
strings.TrimPrefix("ab", "a")
}
```
`gore` is a very good tool.  Thank you :)

Support auto-importing

---

main.go
quickfix.go

I want to import package from external golang source. 
This pull request enables that by `-include` option. 
```bash
$ cd $GOPATH/src/github.com/motemen/gore
$ gore -include main.go
gore version 0.0.0  :help for help
gore> homedir.Dir()
"/Users/tcnksm"
nil
gore>
```
I'm not sure implicit vs. explicit import  (cf. https://github.com/motemen/gore/pull/2)
But for me, session should be what I expected like ruby's `irb`. 
This is just proposal.

Import packages from external golang source code

---

commands.go

Scope.LookupParent takes additional argument(position parameter).
See also
- https://go.googlesource.com/tools/+/665374f1c86631cf73f4729095d4cf4313670545
This is related #22.

Fix for newer interface

---

main.go
session_test.go

Usage:
- `-pkg=<package path>`
- `-pkg=<directory>`
```
% gore -pkg=github.com/motemen/gore
gore version 0.1.0  :help for help
added file /Users/motemen/dev/go/src/github.com/motemen/gore/commands.go
added file /Users/motemen/dev/go/src/github.com/motemen/gore/complete.go
added file /Users/motemen/dev/go/src/github.com/motemen/gore/liner.go
added file /Users/motemen/dev/go/src/github.com/motemen/gore/log.go
added file /Users/motemen/dev/go/src/github.com/motemen/gore/main.go
added file /Users/motemen/dev/go/src/github.com/motemen/gore/node.go
added file /Users/motemen/dev/go/src/github.com/motemen/gore/quickfix.go
added file /Users/motemen/dev/go/src/github.com/motemen/gore/terminal_unix.go
added file /Users/motemen/dev/go/src/github.com/motemen/gore/utils.go
gore> version
"0.1.0"
```

Add -pkg flag to specify the session's context package

---

quickfix.go
session_test.go

some builtins are expected to have side effects

---

README.adoc

Hello.
README nano-fix, in order to avoid certain situations, like #43, when user use readme-copy-paste-kung-fu for installing a packages (like me :)).

README 'go get' statements update

---

.travis.yml

The node formatting may differ from stable APIs and cannot be predicted

Do not test Go tip on travis

---

.travis.yml
commands.go
main.go
quickfix.go

This is similar to https://github.com/motemen/go-quickfix/pull/4 and related to #63.
However `TestNormalizeNodePos` in node_test.go is failed(with Go 1.6) which is not related to this PR. `go/printer.Fprint` sets needless indentations. I got following output.
```go
package P
import "fmt"
func F() {
fmt.
Println(
1,
)
}
```
Expected result is here.
```go
package P
import "fmt"
func F() {
fmt.
Println(
1,
)
}
```

Fix for newer go

---

liner.go
main.go

The runtime error is raised if close braces are greater than open braces
(Then strings.Repeat(indent, negative_number) is called). This change
checks it and clears state if input is wrong.
This is related to #61.
CC: @willfaught
```
% gore
gore version 0.2.5  :help for help
gore> if "a" == " {
panic: runtime error: makeslice: len out of range
goroutine 1 [running]:
strings.Repeat(0x762228, 0x4, 0xffffffffffffffff, 0x0, 0x0)
/opt/go/src/strings/strings.go:464 +0x5f
main.(*contLiner).promptString(0xc820212140, 0x0, 0x0)
/home/syohei/go/src/github.com/motemen/gore/liner.go:33 +0x54
main.(*contLiner).Reindent(0xc820212140)
/home/syohei/go/src/github.com/motemen/gore/liner.go:81 +0xfc
main.main()
/home/syohei/go/src/github.com/motemen/gore/main.go:119 +0xb16
goroutine 5 [syscall]: …
```

Fix unmatched braces issue

---

README.adoc

Fixes the following issue trying to install `go-spew`:
```
$ go get -u github.com/davecgh/go-spew
package github.com/davecgh/go-spew: no Go files in /Users/user/Go/src/github.com/davecgh/go-spew
```

Fix go-spew installation command in README

---

gocode/gocode_test.go

This fixes the error reported by Go 1.10 (that runs `go vet` with `go test`) on Travis:
```
$ go test ./...
gocode/gocode_test.go:12: Error call has possible formatting directive %#v
ok  	github.com/motemen/gore	5.837s
FAIL	github.com/motemen/gore/gocode [build failed]
```

Fix error format

---

main.go

This replaces mysterious paths like `/tmp/273999620` with identifiable `/tmp/gore-273999620`.

Prefix temporary session directories with "gore-"

---

.travis.yml

Testing with go:tip takes 5 minutes while go:1.x finishes within 1 minute.

remove testing with go:tip on TravisCI

---

main.go

So that the banner can be redirected to /dev/null for one-liners or script integration where we are interested in the actual output only. The banner should be used only for interactive mode. ;)

[suggestion] output gore banner to stderr

---

commands_test.go
session_test.go

So that I can see the error when stdout test is failed.

use assert.Equal instead of require.Equal for output tests

---

commands.go
commands_test.go

Go 1.12 removes support for `godoc` in favor of `go doc`.
See https://tip.golang.org/doc/go1.12#godoc for details
Tested in Go 1.12rc1 using the following `Dockerfile`:
```
FROM golang:rc-stretch
WORKDIR /usr/local/src/gore
COPY . .
RUN go mod download > /dev/null 2>&1
CMD go test -v ./...
```
```
$ docker build -t gore:latest .
Sending build context to Docker daemon  10.99MB
Step 1/5 : FROM golang:rc-stretch
---> 553b7c7900d8
Step 2/5 : WORKDIR /usr/local/src/gore
---> Using cache
---> 64bcd9b4b26e
Step 3/5 : COPY . .
---> 5d4991b2da28
Step 4/5 : RUN go mod download > /dev/null 2>&1
---> Running in fb2c415d7ec0
Removing intermediate container fb2c415d7ec0
---> 2783783f1b4e
Step 5/5 : CMD go test -v ./...
---> Running in 2dde6b12fde9
Removing intermediate container 2dde6b12fde9
---> …
```

Fix :doc command in Go 1.12

---

commands_test.go
main.go

- support spaces in the command prefix (ex: `: : :   help`)
- report command not found
- add more tests

Refactor commands

---

command_name.go
commands.go
commands_test.go
complete.go
complete_test.go
session.go

Like Vim, implemented command abbreviations.
```go
~/.go/src/github.com/motemen/gore gore
gore version 0.3.0  :help for help
gore> :i fmt
gore> :w
Source wrote to gore_session_20190224_015549.go
gore> :h
:import <package>     import a package
:print                print current source
:write [<file>]       write out current source
:clear                clear the codes
:doc <expr or pkg>    show documentation
:help                 show this help
:quit                 quit the session
gore> :q
~/.go/src/github.com/motemen/gore
```

Implement command abbreviation

---

.travis.yml
README.adoc
complete.go
gocode/gocode.go

nsf/gocode is deprecated in favor of mdempsky/gocode.

Improve gocode

---

README.md

The godoc is no longer needed to show document.

drop godoc requirements from README.md

---

Makefile
cli.go
cli/cli.go
cli/cli_test.go
cli/run.go
cmd/gore/main.go
gore.go
option.go
version.go

This is related to  #131 but make gore possible to use from another package. I created cli package and moved args parsing to it. Users can initialize Gore struct with functional options and call Run.
Related issues: #4, #14, #74, #79, #131.

Create cli package and make gore usable from another package

---

session.go

This is a simple solution not to overwrite go module files (ref: #143).

Change the directory of go run to the temporary directory

---

README.md

Until https://github.com/golang/go/issues/30515 is resolved. Ref: https://github.com/motemen/gore/issues/143#issuecomment-482031727.

set GO111MODULE=off explicitly to get tools in README.md

---

commands.go
errfilter.go
errfilter_test.go

This pull request changes the directory of go doc to the temporary directory. Also ignores a warning to make the tests pass. I can't understand why `GO111MODULE=on go doc strings.Join` at home directory emits a warning to stderr.

set the directory to the temporary directory on :doc command

---

go.mod
go.sum
gore.go

Now that we can use os.UserHomeDir in Go 1.12+, I removed the library dependency to github.com/mitchellh/go-homedir.

remove github.com/mitchellh/go-homedir dependency

---

Makefile
README.md

When a tool is expected to be built with modules on, it is not good to forcibly disable the modules.

do not disable Go Modules on getting Go tools

---

Makefile

ensure make clean removes the executable

---

session_test.go

Because Go 1.14 (beta) changes the message to `type untyped foo` for constants. (maybe https://go-review.googlesource.com/c/go/+/187657)

tweak error messages in eval func tests

---

README.md

`go version go1.11.1 darwin/amd64`
An error occurred caused by commands below.
```
$  go get -u github.com/motemen/gore/cmd/gore
go/1.11.1/src/github.com/motemen/gore/gore.go:142:14: undefined: os.UserHomeDir
```
**On go1.12, the installation succeeded.**
UserHomeDir is only available go1.12 or later.
https://github.com/motemen/gore/blob/d2d6a78129f3580de982be30d36e341161b04e58/gore.go#L142
c.f.  https://golang.org/doc/go1.12#os
I would like to add the supported version to README.md.

Add supported version to README.md

---

Dockerfile

Follow up of #186. Using `make` fills the revision with `-version` flag.

Update Dockerfile: build using the local code

---

gomod.go
session.go
session_gomod_test.go

This is required since Go 1.16.

fix -autoimport flag by go get -d modules for Go 1.16

---

README.md

This flag disables gomod and we can't ensure it works well.

remove -u flag from installation instruction

---

.github/workflows/ci.yaml
Dockerfile
Makefile
README.md
go.mod

Since 1.17 is about to be released, we now require 1.16 as the minimum version support.

Bump up Go to 1.16

---

Makefile
complete.go
quickfix.go
session_gomod_test.go

Due to golint deprecation, we now switch to staticcheck.

Switch from golint to staticcheck

---

session.go

Without this, sometimes I get error with `-autoimport` mode.

Specify `-mod=mod` for `go run` command to resolve modules
