- LICENSE
- README.adoc
ref: https://github.com/motemen/gore/issues/7
> Clearify the license as MIT

- commands.go
- complete.go
- complete_test.go
- gocode.go
- gocode_test.go
- helpers_test.go
... and now `fmt.p` completes to `fmt.Print` instead of `fmt.print`
> Completion for :doc

- commands.go
- commands_test.go
- main.go
- node_test.go
- quickfix.go
- session_test.go
- utils.go
Separate quickfixing code to go-quickfix for simplicity
> Use motemen/go-quickfix

- quickfix.go
- session_test.go
> isPureExpr for ast.ParenExpr

- liner.go
> Ctrl-C cancels input

- README.adoc
> Doc to make sure to have $GOPATH/bin in $PATH

- README.adoc
- commands.go
- main.go
> Add `:quit` command

- main.go
- node.go
- session_test.go
> Fix const undefined

- commands.go
> :import statement should work with multiple packages

- main.go
> bumped version to 0.3.0

- README.adoc
To make things clearer for newbies.
> Some additional things in the documentation

- README.adoc
This is a point of confusion as seen here https://github.com/motemen/gore/issues/69
> include note on importing local packages in README

- complete.go
- complete_test.go
> exclude __gore_p from completion candidates

- main.go
Please do not forget to close files after opening.
> close files

- commands.go
- commands_test.go
- complete_test.go
- main.go
- node_test.go
- session_test.go
This pull request make the writers to be injectable for testability.
> Injectable writers

- errfilter.go
- main.go
- session_test.go
> improve stderr

- quickfix.go
- session_test.go
> Fix evaluated but not used

- commands.go
- main.go
- session_test.go
close #34, close #76, close #102.
TODO: restoreMainBody
> Implement function declaration

- commands.go
- commands_test.go
- main.go
> Implement clear command

- main.go
- session_test.go
fix  #17 
```go
$ gore
gore version 0.3.0  :help for help
gore> foo\bar
invalid token: "\\"
gore> #foo
invalid token: "#"
gore> ?
invalid token: "?"
gore>
```
> Report token errors

- complete.go
- complete_test.go
> Change line head tab key indentatation

- complete.go
- complete_test.go
Improve completion support for #122
> Improve command complete

- command_name_test.go
> Add tests for command name

- commands.go
- commands_test.go
- complete_test.go
```go
$ gore
gore version 0.3.0  :help for help
gore> :t 3.14
float64
gore> x := "foo"
"foo"
gore> :t x
string
gore> :i fmt
gore> :t fmt.Sprintf
func(format string, a ...interface{}) string
gore> :t fmt.Sscanf
func(str string, format string, a ...interface{}) (n int, err error)
```
> Implement type command

- errfilter.go
- errfilter_test.go
- session.go
Improved implementation of #112.
> Rewrite error filter with Transformer

- session.go
- session_test.go
> Print values of variable declaration

- gore.go
- Print values of variable declaration  #140
- Create cli package and make gore usable from another package #145 
- Change the directory of go run to the temporary directory #147
> bump up version to 0.4.1

- .gitignore
- Makefile
These days I stopped using build/ directory for simplicity.
> change the output path of make build

- README.md
Updates FAQ
Also mentions on Go modules support of go (ref #174)
> Update FAQ in README.md

- liner.go
> increate indentation depth with parenthesis

- commands.go
- quickfix.go
- session.go
- session_test.go
> fix :type and :doc for -context

- .github/workflows/ci.yaml
- update ci triggers
- update actions/setup-go
> Update ci configuration

- commands.go
- session.go
This pr fixes #192 by enabling module editing mode.
> add -mod=mod build flag to packages.Load

- Dockerfile
- Makefile
- README.md
- cli/cli.go
- cli/cli_test.go
- cmd/gore/main.go
- complete.go
- complete_test.go
- go.mod
- session_gomod_test.go
- session_test.go
We migrated the repository from /motemen/ to /x-motemen/.
> Migrate to x-motemen

- session.go
- session_test.go
> Support struct method declaration
